name: Build NosDeCorda APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Preparar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Preparar Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools'

      - name: Instalar componentes Android
        run: |
          sdkmanager "platforms;android-35"
          sdkmanager "build-tools;35.0.0"

      - name: Verificar Android
        run: |
          java -version
          adb --version
          sdkmanager --list_installed

      - name: Finalizar
        run: |
          echo "Android SDK preparado com sucesso!"